name: vae-pu-env
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - cuda-toolkit=11.3.0
  - pip=23.1.1
  - numpy=1.19.5
  - pandas=1.2
  - matplotlib=3.6.2
  - seaborn=0.11.1
  - scipy=1.8.0
  - scikit-learn=1.0.1
  - pyod=1.0.1
  - statsmodels=0.13.1
  - joblib=1.0.1
  - numba=0.55.1
  - tensorflow=2.3.0
  - keras=2.4.3
  - pytorch=1.10.1
  - torchtext=0.11.1
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - ipykernel=6.17.0
  - ipywidgets=8.0.6
  - protobuf=3.20.0
  - chainer=7.8.1
  - pkbar
  - pip:
      - ucimlrepo==0.0.3
